// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHt0AEzO14JzLcWlBO_WLcIiqXh4nOHb0',
    appId: '1:402837791555:web:eec5d337269427161005f6',
    messagingSenderId: '402837791555',
    projectId: 'billbook-aliwhosane',
    authDomain: 'billbook-aliwhosane.firebaseapp.com',
    storageBucket: 'billbook-aliwhosane.appspot.com',
    measurementId: 'G-ZRQ6STS8Z4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqjwV9lXsqR5L-HKyIFFG1vvvlKjHwdsg',
    appId: '1:402837791555:android:9ad2bc3c96f322261005f6',
    messagingSenderId: '402837791555',
    projectId: 'billbook-aliwhosane',
    storageBucket: 'billbook-aliwhosane.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOSL6UM5MNSGToz51q70c9O2ubfuDEsh0',
    appId: '1:402837791555:ios:9bc7d75525e0f1aa1005f6',
    messagingSenderId: '402837791555',
    projectId: 'billbook-aliwhosane',
    storageBucket: 'billbook-aliwhosane.appspot.com',
    iosClientId: '402837791555-do5b9jnct588e2rjqai813amk9vhlp71.apps.googleusercontent.com',
    iosBundleId: 'com.billbook.billbook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOSL6UM5MNSGToz51q70c9O2ubfuDEsh0',
    appId: '1:402837791555:ios:9bc7d75525e0f1aa1005f6',
    messagingSenderId: '402837791555',
    projectId: 'billbook-aliwhosane',
    storageBucket: 'billbook-aliwhosane.appspot.com',
    iosClientId: '402837791555-do5b9jnct588e2rjqai813amk9vhlp71.apps.googleusercontent.com',
    iosBundleId: 'com.billbook.billbook',
  );
}
